<?php
require_once __DIR__.'/../includes/admin_layout.php';
$orders=readJson(__DIR__.'/../data/orders.json'); $users=readJson(__DIR__.'/../data/users.json'); $menu=readJson(__DIR__.'/../data/menu.json'); $inv=readJson(__DIR__.'/../data/inventory.json'); $offers=readJson(__DIR__.'/../data/offers.json');
$sales=0;$pending=0;$completed=0;$cancelled=0; foreach($orders as $o){$s=strtolower($o['status']??''); if($s!=='cancelled')$sales+=(float)($o['total']??0); if(in_array($s,['new','preparing','ready'],true))$pending++; if($s==='completed')$completed++; if($s==='cancelled')$cancelled++;}
$customers=count(array_filter($users,fn($u)=>($u['role']??'')==='customer')); $low=count(array_filter($inv,fn($i)=>(int)($i['quantity']??0)<=(int)($i['minimum']??0))); $activeProducts=count(array_filter($menu,fn($p)=>!empty($p['available']))); $activeOffers=count(array_filter($offers,fn($o)=>!empty($o['active'])));
adminStart('Dashboard','dashboard'); ?>
<section class="stat-grid">
<div class="admin-stat"><span>📦</span><div><small>Total Orders</small><strong><?=count($orders)?></strong></div></div><div class="admin-stat"><span>💰</span><div><small>Total Sales</small><strong>₹<?=number_format($sales,2)?></strong></div></div><div class="admin-stat"><span>👥</span><div><small>Customers</small><strong><?=$customers?></strong></div></div><div class="admin-stat"><span>🍔</span><div><small>Active Products</small><strong><?=$activeProducts?></strong></div></div><div class="admin-stat"><span>⏳</span><div><small>Pending Orders</small><strong><?=$pending?></strong></div></div><div class="admin-stat"><span>⚠️</span><div><small>Low Stock</small><strong><?=$low?></strong></div></div></section>
<div class="quick-grid"><a href="products.php" class="quick-card">➕ <b>Add Product</b><small>Manage menu items</small></a><a href="orders.php" class="quick-card">📦 <b>Manage Orders</b><small><?=$pending?> active orders</small></a><a href="inventory.php" class="quick-card">📋 <b>Inventory</b><small><?=$low?> low-stock items</small></a><a href="offers.php" class="quick-card">🏷️ <b>Offers</b><small><?=$activeOffers?> active offers</small></a></div>
<div class="admin-panels"><section class="admin-panel"><div class="panel-head"><h2>Recent Orders</h2><a href="orders.php">View all →</a></div><div class="table-wrap"><table><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th></tr><?php foreach(array_slice(array_reverse($orders),0,8) as $o): ?><tr><td>#<?=h($o['order_id']??'')?></td><td><?=h($o['customer_name']??'')?></td><td>₹<?=number_format((float)($o['total']??0),2)?></td><td><span class="badge <?=h(strtolower($o['status']??'new'))?>"><?=ucfirst(h($o['status']??'new'))?></span></td><td><?=h($o['created_at']??'')?></td></tr><?php endforeach; ?></table></div></section>
<section class="admin-panel"><div class="panel-head"><h2>Inventory Alerts</h2><a href="inventory.php">Manage →</a></div><?php $alerts=array_filter($inv,fn($i)=>(int)($i['quantity']??0)<=(int)($i['minimum']??0)); if(!$alerts): ?><div class="empty">✅ All inventory levels are healthy.</div><?php else: foreach($alerts as $i): ?><div class="alert-row"><span>⚠️ <?=h($i['name'])?></span><b><?=h($i['quantity'])?> <?=h($i['unit'])?></b></div><?php endforeach; endif; ?></section></div>
<?php adminEnd(); ?>